# https://taskfile.dev

version: "3"

output: prefixed

tasks:
  default:
    cmd: task --list-all
    prefix: help

  pocket:
    cmd: bun run pocket

  astro:
    cmd: bun run dev

  dev:
    deps: [pocket, astro]
    interactive: true

  build:
    cmds:
      - bun run pocket &
      - defer: sh -c "kill $(lsof -ti :9090) 2>/dev/null" || true
      - sleep 3
      - bun run build
